### ISSUE TITLE
LinkedIn URL Correction

### ISSUE THREAD

**Issue by JuanPabloDiaz** [BaronVonPerko/perko-dev#9]
Hello Chris,

I noticed that your LinkedIn URL might be missing a hyphen `-`. 

- The current URL is: https://www.linkedin.com/in/chrisperko
- It seems like it should be: https://www.linkedin.com/in/chris-perko

I like your minimalist site!
I hope this helps!

Best regards,
[Juan Diaz](https://www.linkedin.com/in/1diazdev)

**Comment by BaronVonPerko** [comment]
Wow, thanks so much! I'll update that now!
